# flake8: noqa

"""All exceptions used by puslib.
"""


class PusException(Exception): ...
class CrcException(PusException): ...
class IncompletePacketException(PusException): ...
class InvalidPacketException(PusException): ...
class TooSmallBufferException(PusException): ...
class InvalidTimeFormat(PusException): ...
class TcPacketRoutingError(PusException): ...
